spring.application.name=online-shop-spring-boot-backend

//connect postgreSQL database
spring.datasource.url=jdbc:postgresql://dpg-d7qqnngg4nts73c700cg-a.oregon-postgres.render.com:5432/onlineshop_ksgt
spring.datasource.username=mqb
spring.datasource.password=hm3ntjBUAqRD9ncM1RaaXjzN1acYmu8P

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect